services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-authy}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@db/${POSTGRES_DB:-authy}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY:-cYLcVxWRSrY0tUhsDcmJ4jbx0HuYAY34mz42nQ5v3_k=}
    depends_on:
      - db
    ports:
      - "8041:8041"

  frontend:
    build: ./frontend
    ports:
      - "8040:80"

volumes:
  postgres_data: